package com.vedeng.ordergoods.dao;

import com.vedeng.ordergoods.model.SaleorderGoodsGenerate;
import com.vedeng.ordergoods.model.SaleorderGoodsGenerateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleorderGoodsGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    long countByExample(SaleorderGoodsGenerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int deleteByExample(SaleorderGoodsGenerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int deleteByPrimaryKey(Integer saleorderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int insert(SaleorderGoodsGenerate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int insertSelective(SaleorderGoodsGenerate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    List<SaleorderGoodsGenerate> selectByExample(SaleorderGoodsGenerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    SaleorderGoodsGenerate selectByPrimaryKey(Integer saleorderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleorderGoodsGenerate record, @Param("example") SaleorderGoodsGenerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int updateByExample(@Param("record") SaleorderGoodsGenerate record, @Param("example") SaleorderGoodsGenerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int updateByPrimaryKeySelective(SaleorderGoodsGenerate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Wed Apr 17 19:46:31 CST 2019
     */
    int updateByPrimaryKey(SaleorderGoodsGenerate record);
}