package com.vedeng.firstengage.dao;

import com.vedeng.firstengage.model.FirstEngage;
import com.vedeng.firstengage.model.RegistrationNumber;

import java.util.List;
import java.util.Map;

public interface RegistrationNumberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_REGISTRATION_NUMBER
	 * @mbg.generated  Wed Mar 20 18:32:35 CST 2019
	 */
	int deleteByPrimaryKey(Integer registrationNumberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_REGISTRATION_NUMBER
	 * @mbg.generated  Wed Mar 20 18:32:35 CST 2019
	 */
	int insert(RegistrationNumber record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_REGISTRATION_NUMBER
	 * @mbg.generated  Wed Mar 20 18:32:35 CST 2019
	 */
	int insertSelective(RegistrationNumber record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_REGISTRATION_NUMBER
	 * @mbg.generated  Wed Mar 20 18:32:35 CST 2019
	 */
	RegistrationNumber selectByPrimaryKey(Integer registrationNumberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_REGISTRATION_NUMBER
	 * @mbg.generated  Wed Mar 20 18:32:35 CST 2019
	 */
	int updateByPrimaryKeySelective(RegistrationNumber record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_REGISTRATION_NUMBER
	 * @mbg.generated  Wed Mar 20 18:32:35 CST 2019
	 */
	int updateByPrimaryKey(RegistrationNumber record);

	/**
	 * registrationNumberMapper根据输入查询注册证
	 * <p>Title: getRegistrationInfoByStr</p>  
	 * <p>Description: </p>  
	 * @param paramMap
	 * @return  
	 * @author Bill
	 * @date 2019年3月21日
	 */
	List<RegistrationNumber> getRegistrationInfoByStr(Map<String, Object> paramMap);

	/**
	 * 查询注册证信息
	 * <p>Title: getRegistrationInfoById</p>  
	 * <p>Description: </p>  
	 * @param paramMap
	 * @return  
	 * @author Bill
	 * @date 2019年3月27日
	 */
	RegistrationNumber getRegistrationInfoById(Map<String, Object> paramMap);

	/**
	 * @description 根据注册证号查询注册证信息
	 * @author bill
	 * @param
	 * @date 2019/4/24
	 */
    RegistrationNumber getRegistrationInfoByNumber(String registrationNumber);

    /**
     * @description 刷临效期状态
     * @author bill
     * @param
     * @date 2019/5/28
     */
    void refreshFirstList(Map<String, Object> param);

	List<RegistrationNumber> getRefreshFirstList(Map<String, Object> paramMap);


    Integer dealstatus(Integer registrationNumberId);


    List<RegistrationNumber> getPCInfo();


    void insertList(List<RegistrationNumber> list);

	List<RegistrationNumber> getHisRegFromGoods();
}